### ISSUE TITLE
Something looks weird with the bundled js

### ISSUE THREAD

**Issue by sarbull** [emyann/typescript-webpack-starter#6]
![screen shot 2017-07-18 at 10 03 15](https://user-images.githubusercontent.com/1864112/28304448-62be463a-6ba0-11e7-87b6-753b4bbf8881.png)

**Comment by emyann** [comment]
👋🏽 Hi @sarbull ! Thank you for your feedback! 🙏🏽 Your issue is resolved with the latest version of master!
<img width="1920" alt="screen shot 2017-07-19 at 5 31 41 pm" src="https://user-images.githubusercontent.com/4748419/28390577-9cb78db6-6ca8-11e7-88ef-2587a00640a5.png">

You could just pull the last changes from Master since we have just updated the starter pack to support Unit Tests with Karma! Moreover we now use `Webpack 3` so you don't need to fight with all the breaking changes :) 

Enjoy, and let me know if everything is ok before I close this issue :)
